# Indexing

In [13]:
import torch

## Integer Tensor Indexing

使用数组来索引tensor中的数据，得到tensor的子视图，**数组中的是需要索引的批、行、列等等**，其余维度上用 `:` 指代。

In [14]:
a = torch.arange(0, 35).reshape(5, 7)
print(a)

# 得到第0, 3, 5, 6列组尘的tensor
b = a[:, [0, 3, 5, 6]]
print(b)

# 得到1, 0, 1, 3行组成的tensor
c = a[[1, 0, 1, 3], :]
print(c)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]])
tensor([[ 0,  3,  5,  6],
        [ 7, 10, 12, 13],
        [14, 17, 19, 20],
        [21, 24, 26, 27],
        [28, 31, 33, 34]])
tensor([[ 7,  8,  9, 10, 11, 12, 13],
        [ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [21, 22, 23, 24, 25, 26, 27]])


另一种使用Integer Tensor Indexing的方式是每个维度都用相同长度的数组进行索引。

In [15]:
# 得到a[0, 1], a[2, 3], a[4, 6]上的元素组成的一维张量
d = a[[0, 2, 4], [1, 3, 6]]
print(d)

tensor([ 1, 17, 34])


## Boolean Tensor Indexing

通过与原tensor相同形状的bool类型tensor筛选出值为 `True` 的元素，并组成一维张量。 

In [16]:
e = a[a > 20]
print(e)

f = a[a % 7 == 0]
print(f)

tensor([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])
tensor([ 0,  7, 14, 21, 28])
