# 常用函数

In [1]:
import torch

## torch.cat

将几个不同的tensor拼接在一起，可以指定按照哪个维度对齐进行拼接，**其余维度大小必须相同**。

In [2]:
x = torch.arange(15).reshape(3, 5)
print(x)
y = torch.arange(12).reshape(3, 4)
print(y)

# 按照列对齐进行拼接 
z = torch.cat([x, y], dim=1)
print(z)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  0,  1,  2,  3],
        [ 5,  6,  7,  8,  9,  4,  5,  6,  7],
        [10, 11, 12, 13, 14,  8,  9, 10, 11]])


三维tensor的拼接。

In [3]:
x = torch.arange(18).reshape(2, 3, 3)
print(x)
y = torch.arange(9).reshape(1, 3, 3)
print(y)

# 按照批对齐进行拼接
z = torch.cat([x, y], dim=0)
print(z)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]]])


## torch.topk

用于选出张量中最大\小的k个元素，返回值和索引：`torch.topk(input, k, dim=None, largest=True, sorted=True)`

- `input`: 张量
- `k`: 多少个元素
- `dim`: 选取维度
- `largest`: 为 `True` 时，选取最大的k个；为 `False` 时，选取最小的k个
- `sorted`: 是否需要排序 

In [9]:
x = torch.rand(1, 10)
print(x)

# 得到最大2个数的值和索引
values, indices = x.topk(2, largest=True)
print(values)
print(indices)

tensor([[0.9723, 0.1026, 0.8597, 0.3308, 0.3132, 0.7276, 0.2354, 0.2993, 0.7812,
         0.3810]])
tensor([[0.9723, 0.8597]])
tensor([[0, 2]])


## torch.mode

mode的意思就是众数，用于**整数类型张量**，返回出现次数最多的元素和次数，可以指定维度，在相应维度上查看众数。

In [13]:
x = torch.tensor([1, 2, 4, 3, 1, 6, 5, 7, 3, 7, 5, 9])
print(x)

# 得到众数和出现次数
mode, times = x.mode()
print(mode)
print(times)

y = x.view(3, 4)
print(y)

mode, times = y.mode(dim=0)
print(mode)
print(times)

tensor([1, 2, 4, 3, 1, 6, 5, 7, 3, 7, 5, 9])
tensor(1)
tensor(4)
tensor([[1, 2, 4, 3],
        [1, 6, 5, 7],
        [3, 7, 5, 9]])
tensor([1, 2, 5, 3])
tensor([1, 0, 2, 0])
